### ISSUE TITLE
Can follow the instructions for CentOS 7?

### ISSUE THREAD

**Issue by pvanthony** [nkadel/samba4repo#1]
Can follow the instructions for CentOS 7?

Just by changing the 6 --> 7?

**Comment by nkadel-skyhook** [comment]
Haven't tested this month, but I had things set up to build for CentOS 6 and 7 with mock.

Nico Kadel-Garcia
Email: nkadel@gmail.commailto:kadel@gmail.com
Sent from iPhone

On Apr 5, 2016, at 11:28, "P.V.Anthony" <notifications@github.com<mailto:notifications@github.com>> wrote:

Can follow the instructions for CentOS 7?

Just by changing the 6 --> 7?

**Comment by pvanthony** [comment]
Thank you for the reply.

I will learn how to use mock and test it out.

**Comment by nkadel** [comment]
Samba 4.4  is definitely not going to be possible to backport to RHEL or CentOs 7: it depends on too recent a version of gnutls.
