### ISSUE TITLE
4.16.0 and GnuTLS >= 3.7.2 for CentOS7

### ISSUE THREAD

**Issue by frspackager** [nkadel/samba4repo#11]
Hello, just checking if you plan to provide an update for compat-gnutls to 3.7.2 or higher or if you dropped support for CentOS7. I don't think nettle is impacted.

Another minor thing, a fresh `git clone --recurse-submodules` comes with `ssh://` urls for the modules and fails if you have no GitHub account setup.

Thanks in advance for your help.

**Comment by frspackager** [comment]
Closing issue, I did not recurse properly in the compat modules. Sorry.

**Comment by nkadel** [comment]
I've also dropped support for RHEL 7 and the matching compat-gnutls requirement.
