### ISSUE TITLE
Error building libtalloc

### ISSUE THREAD

**Issue by avrhack** [nkadel/samba4repo#2]
Building on Centos 7.5 with the versions as of today I get the following build errors:

Obsoletes: pytalloc < 2.1.3 python-talloc < 2.1.14-0.el7
Processing files: python2-talloc-devel-2.1.14-0.el7.x86_64
error: File must begin with "/": %ldconfig_scriptlets
error: File must begin with "/": %ldconfig_scriptlets
error: File must begin with "/": -n
error: File must begin with "/": python2-talloc

RPM build errors:
    File must begin with "/": %ldconfig_scriptlets
    File must begin with "/": %ldconfig_scriptlets
    File must begin with "/": -n
    File must begin with "/": python2-talloc
make: *** [build] Error 1

**Comment by nkadel** [comment]
Are you using “mock” to do the build?

**Comment by avrhack** [comment]
I followed the ordering in the README yes, ie make cfgs, make repos, make, make build.

However just to be sure I did a make clean then did that sequence again and there's actually an earlier error at the 'make' stage of "error: unknown option `recurse-submodules'" so I guess either you're using a newer version of git than the latest standard Centos build, or you've customised your version of git in some way with aliases?

**Comment by nkadel** [comment]
*Oh*. I have git updated locally, with https://github.com/nkadel/git218-srpm. I've revised this, and I think I've dealt with the ldconfig issues. Do a fresh pull.

I'm afraid the current samba-4.9.2 release has *zero* chance of building on CentOS 7, due to dependencies on a more recent version of gnutls. I might be able to get it to build samba-4.8.6 successfully, but haven't been spending time to support that.

**Comment by avrhack** [comment]
Ah that explains it thanks! Will do the pull as you suggest, however it's really 4.9.2 that I'm after as I want to try and finally get rid of Netatalk which needs Samba's time machine support and therefore..... 4.9.2! :)

I'm guessing that there's no way to set the configuration up to omit TLS support from the build? I don't use encrypted transport so don't think I need it unless TLS is mandatory and or used for something else within samba?

**Comment by nkadel** [comment]
I build 4.9.x to activate the full domain controller features. Maybe you can reset with_dc and avoid the dependency? Or use the Serney RPMs ?

**Comment by nkadel** [comment]
That is”Sernet RPMs” . I can’t swear if they have full domain controller features activated.

**Comment by nkadel** [comment]
OK, try it now. You will probably have to build it on fedora 29 to use mock, because of the hooks for that OS, and because the CentOS based .cfg looks for keys in places that exist on that OS as part of "mock", not as part of CentOS 7.

**Comment by avrhack** [comment]
Thanks for the quick replies. Gets further now but fails with:

find: 'epel-7-x86_64': No such file or directory
	Building epel-7-x86_64 RPMS with libtalloc.spec
You are attempting to run "mock" which requires administrative
privileges, but more information is needed in order to do so.
Authenticating as "root"
Password:
ERROR: Exception(libtalloc.spec) Config(epel-7-x86_64) 4 minutes 11 seconds
ERROR: Command failed. See logs for output.

**Comment by nkadel** [comment]
On Mon, Nov 26, 2018 at 2:06 AM avrhack <notifications@github.com> wrote:

> Thanks for the quick replies. Gets further now but fails with:
>
> find: 'epel-7-x86_64': No such file or directory
> Building epel-7-x86_64 RPMS with libtalloc.spec
> You are attempting to run "mock" which requires administrative
> privileges, but more information is needed in order to do so.
> Authenticating as "root"
>
> "mock" works much better if you first add your user account to the group
"mock".

sudo usemod -a -G mock $USER

**Comment by avrhack** [comment]
Doh! As you can tell I haven't used mock before..... Really appreciate the help thanks, however still no joy. Error very similar.....

Sqlite DBs complete
(cd libtalloc-srpm; make  install)
make[1]: Entering directory `/usr/src/samba4repo/libtalloc-srpm'
find: 'epel-7-x86_64': No such file or directory
	Building epel-7-x86_64 RPMS with libtalloc.spec
ERROR: Exception(libtalloc.spec) Config(epel-7-x86_64) 0 minutes 24 seconds
ERROR: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/libtalloc.spec
Storing epel-7-x86_64/*.src.rpm in epel-7-x86_64.rpm
/bin/mv: cannot stat 'epel-7-x86_64/*.src.rpm': No such file or directory
Actally building RPMS in epel-7-x86_64
ERROR: Cannot find/open srpm: epel-7-x86_64.src.rpm. Error: [Errno 2] No such file or directory: 'epel-7-x86_64.src.rpm'
make[1]: *** [epel-7-x86_64] Error 1
make[1]: Leaving directory `/usr/src/samba4repo/libtalloc-srpm'
make: *** [libtalloc-srpm] Error 2

**Comment by nkadel** [comment]
I've updated to samba-4.10.x. Have you seen any of this recur?

**Comment by nkadel** [comment]
That last problem was apparently due to failing to start the build in the top level, where it automatically sets up the various local .cfg files. It was easier to write the syntax to use "../name.cfg" rather than figure out which ones are created locally, and which ones are in /etc/mock/. Since it's been over six months, I'm going to mark this one closed. Reach out if you have more issues.
