### ISSUE TITLE
python2-talloc conflicts on EL7

### ISSUE THREAD

**Issue by sprintman** [nkadel/samba4repo#3]
python2-talloc-2.1.14 obseletes pytalloc < 2.1.3, but the current release in Centos 7.6 is pytalloc-2.1.13.

Whilst is is easy to bump the version in the spec file, I would prefer if it kept the pytalloc package name so as to not cause issues with future Centos updates. (Same with python-tdb/python2-tdb)

**Comment by nkadel** [comment]
On Tue, Feb 26, 2019 at 7:30 PM sprintman <notifications@github.com> wrote:

> python2-talloc-2.1.14 obseletes pytalloc < 2.1.3, but the current release
> in Centos 7.6 is pytalloc-2.1.13.
>
> Whilst is is easy to bump the version in the spec file, I would prefer if
> it kept the pytalloc package name so as to not cause issues with future
> Centos updates. (Same with python-tdb/python2-tdb
>
pytalloc is blatantly misnamed. I'm reluctant to continue what was an
exceptionally foolish package name.

**Comment by sprintman** [comment]
Can this cause conflicts when, say, Centos 7.7 is released with pytalloc-2.1.20? I don't know all the intricacies of how RPM/YUM works, but it seems prudent to keep the official distribution package name where possible.

**Comment by nkadel** [comment]
It may require manual attention when doing a "yum -y update", but I was pretty careful to use "Provides:" and "Conflicts:" and "Obsoletes:" for modules from upsream that violated the python module naming convictions.
