### ISSUE TITLE
References ldb 2.1 but submodule is ldb 2.2

### ISSUE THREAD

**Issue by abartlet** [nkadel/samba4repo#7]
I was trying to rebuild this and and had to fix the Makefile:

https://github.com/nkadel/samba4repo/blob/e9fe884f98b8d176c59a66f83a828646bf352cfb/Makefile#L29

**Comment by abartlet** [comment]
It turns out the issue is the reverse: Samba 4.12 requires ldb 2.1 (and is not compatible with 2.2).  We require exactly the ldb version that Samba shipped with.

**Comment by nkadel** [comment]
Use the v4.12.5 tag for now, "master" got updated when libldb 2.2.x came out, and I didn't realize that a 4.12.6 or 4.13 release would be held so long.

**Comment by abartlet** [comment]
All Samba 4.12 versions will require ldb 2.1 versions, the exact ones they were released with.  I know it is confusing, I've tried to get this separate ldb release stuff removed (and just make it part of the Samba release) but to no avail so far.

**Comment by abartlet** [comment]
In terms of the 4.13 release, it is still due in September, see https://wiki.samba.org/index.php/Samba_Release_Planning#Upcoming_Release and https://wiki.samba.org/index.php/Release_Planning_for_Samba_4.13

**Comment by nkadel** [comment]
I've updated "master" to build 4.13.0rc1. If you want 4.12.5, use the matching tag. I've been keeping the master for these repos at the bleeding edge, and relying on tags for older releases.

**Comment by nkadel** [comment]
samba-4.13.0 is out and is supported by the "master" release with updated libtdb requirements.
